//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOrder.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DKHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DKHACHHANG()
        {
            this.TDONHANGs = new HashSet<TDONHANG>();
            this.TDONHANGCHITIETs = new HashSet<TDONHANGCHITIET>();
            this.TGIAOHANGs = new HashSet<TGIAOHANG>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DIENTHOAI { get; set; }
        public string TINHTHANH { get; set; }
        public string QUANHUYEN { get; set; }
        public string PHUONGXA { get; set; }
        public string DIACHI { get; set; }
        public string NOTE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DNHOMKHACHHANGID { get; set; }
        public Nullable<int> LOAIVANCHUYEN { get; set; }
        public string DNHAXEID { get; set; }
        public string EMAIL { get; set; }
    
        public virtual DNHAXE DNHAXE { get; set; }
        public virtual DNHOMKHACHHANG DNHOMKHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANG> TDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANGCHITIET> TDONHANGCHITIETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TGIAOHANG> TGIAOHANGs { get; set; }
    }
}
