//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOrder.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCONFIG
    {
        public string ID { get; set; }
        public string THONGBAO { get; set; }
        public string NOIDUNGCHANTRAN { get; set; }
        public string THONGTIN { get; set; }
        public string TTSAUTHANHTOANID { get; set; }
        public string TTTAODIEUPHOIID { get; set; }
        public string TTDANHANID { get; set; }
        public string PICK_NAME { get; set; }
        public string PICK_PROVINCE { get; set; }
        public string PICK_DISTRICT { get; set; }
        public string PICK_WARD { get; set; }
        public string PICK_ADDRESS { get; set; }
        public string PICK_TEL { get; set; }
        public string PICK_EMAIL { get; set; }
        public string TTXACNHANDANHANID { get; set; }
    
        public virtual DTRANGTHAIDON DTRANGTHAIDON { get; set; }
        public virtual DTRANGTHAIDON DTRANGTHAIDON1 { get; set; }
        public virtual DTRANGTHAIDON DTRANGTHAIDON2 { get; set; }
        public virtual DTRANGTHAIDON DTRANGTHAIDON3 { get; set; }
    }
}
