//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOrder.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDONHANG()
        {
            this.TDONHANGCHITIETs = new HashSet<TDONHANGCHITIET>();
        }
    
        public string ID { get; set; }
        public System.DateTime NGAY { get; set; }
        public string NAME { get; set; }
        public Nullable<long> TIENHANG { get; set; }
        public string PHIVANCUYEN { get; set; }
        public Nullable<long> TONGCONG { get; set; }
        public string TINHTHANH { get; set; }
        public string QUANHUYEN { get; set; }
        public string PHUONGXA { get; set; }
        public string DIACHI { get; set; }
        public string DKHACHHANGID { get; set; }
    
        public virtual DKHACHHANG DKHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANGCHITIET> TDONHANGCHITIETs { get; set; }
    }
}
